#**********uniscope-driver-modify-file-on-qualcomm-platform*****************#
#msg2238 touchpanel driver

obj-$(CONFIG_MSG2XXX_TOUCHPANEL_DRV_COMMON)				+= mstar_drv_common.o
obj-$(CONFIG_MSG2XXX_TOUCHPANEL_DRV_QCOM)				+= mstar_drv_qcom.o
obj-$(CONFIG_MSG2XXX_TOUCHPANEL_DRV_IC_FW_PORTING_LAYER)		+= mstar_drv_ic_fw_porting_layer.o
obj-$(CONFIG_MSG2XXX_TOUCHPANEL_DRV_PLATFORM_INTERFACE)			+= mstar_drv_platform_interface.o
obj-$(CONFIG_MSG2XXX_TOUCHPANEL_DRV_PLATFORM_PORTING_LAYER)		+= mstar_drv_platform_porting_layer.o
obj-$(CONFIG_MSG2XXX_TOUCHPANEL_DRV_UTILITY_ADAPTION)			+= mstar_drv_utility_adaption.o
obj-$(CONFIG_MSG2XXX_TOUCHPANEL_DRV_MAIN)				+= mstar_drv_main.o
obj-$(CONFIG_MSG2XXX_TOUCHPANEL_DRV_SELF_FW_CONTROL)			+= mstar_drv_self_fw_control.o

